'use client';

import '@react-sigma/core/lib/style.css';

import { useCallback, useEffect, useRef, useState, useMemo } from 'react';
import { SigmaContainer, useSigma } from '@react-sigma/core';
import Graph from 'graphology';
import type Sigma from 'sigma';
import { useGraphNetwork, useEgoNetwork, useTickerList, useTickerThemes } from '@/hooks/useStories';
import StorylineDossier from './StorylineDossier';
import GraphDataLoader from './GraphDataLoader';
import GraphEvents from './GraphEvents';
import GraphStyle from './GraphStyle';
import CommunityOverlay from './CommunityOverlay';
import { GraphContext } from './GraphContext';
import type { FilterState } from './GraphContext';
import { HelpModal } from '@/components/HelpModal';
import type { HelpSection } from '@/components/HelpModal';
import { COMMUNITY_PALETTE, COMMUNITY_OTHER } from '@/lib/communityColors';

const OTHER_COLOR = COMMUNITY_OTHER;
const TOP_N = COMMUNITY_PALETTE.length; // 15

// ── SigmaRefBridge ────────────────────────────────────────────────────────────
// Bridges the sigma instance (only accessible inside SigmaContainer) to a ref
// in the parent, so CommunityOverlay and camera controls can use it.
function SigmaRefBridge({ sigmaRef }: { sigmaRef: React.MutableRefObject<Sigma | null> }) {
  const sigma = useSigma();
  useEffect(() => {
    sigmaRef.current = sigma;
    return () => { sigmaRef.current = null; };
  }, [sigma, sigmaRef]);
  return null;
}

const SIGMA_SETTINGS = {
  renderLabels: true,
  labelFont: '-apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
  labelSize: 12,
  labelColor: { color: '#E0E0E0' },
  labelRenderedSizeThreshold: 8,
  hideLabelsOnMove: true,
  defaultEdgeColor: 'rgba(150,190,220,0.08)',
  defaultNodeColor: '#00A8E8',
  minCameraRatio: 0.05,
  maxCameraRatio: 5,
  enableEdgeEvents: false,
  hideEdgesOnMove: true,
};

const STORIES_GUIDE_SECTIONS: HelpSection[] = [
  {
    key: 'nodes',
    label: 'Nodes — Storylines',
    labelColor: 'text-orange-300',
    bgColor: 'bg-orange-500/8 border-orange-500/15',
    content: 'Each node is an active narrative storyline. Node size reflects momentum score — larger nodes are gaining coverage. Hover to see the title and article count; click to open the full dossier.',
  },
  {
    key: 'colors',
    label: 'Colors — Communities',
    labelColor: 'text-purple-300',
    bgColor: 'bg-purple-500/8 border-purple-500/15',
    content: 'Colors represent Louvain-detected thematic communities. Up to 15 distinct communities are shown; all others appear in dark gray. Community names are generated by Gemini and shown in the legend.',
  },
  {
    key: 'edges',
    label: 'Edges — Narrative Links',
    labelColor: 'text-cyan-300',
    bgColor: 'bg-cyan-500/8 border-cyan-500/15',
    content: 'Lines connect storylines that share key entities. Edge thickness and opacity correspond to TF-IDF weighted Jaccard similarity — thicker lines indicate stronger narrative overlap.',
  },
  {
    key: 'ego',
    label: 'Ego Network',
    labelColor: 'text-blue-300',
    bgColor: 'bg-blue-500/8 border-blue-500/15',
    content: 'Click a node to enter ego-network mode: the selected node\'s direct neighbors are highlighted. Other nodes become ghost outlines. Click the same node again or press Escape to exit.',
  },
  {
    key: 'filters',
    label: 'Filters',
    labelColor: 'text-green-300',
    bgColor: 'bg-green-500/8 border-green-500/15',
    content: 'Momentum slider — hide storylines below a minimum momentum. Ticker filter — select a market ticker to highlight storylines related to that asset. Community legend — click to isolate.',
    tip: 'Use the ticker filter to find geopolitical narratives with direct market relevance.',
  },
  {
    key: 'status',
    label: 'Status — Node Age',
    labelColor: 'text-yellow-300',
    bgColor: 'bg-yellow-500/8 border-yellow-500/15',
    content: 'Emerging — new storylines (< 3 days). Active — developing threads with recent updates. Stabilized — established narratives with lower but steady activity.',
  },
];

interface StorylineGraphProps {
  highlightId?: number | null;
}

export default function StorylineGraph({ highlightId = null }: StorylineGraphProps) {
  // Stable graphology graph object — never recreated, SigmaContainer holds the WebGL context
  const sigmaGraph = useRef(new Graph({ type: 'undirected', multi: false })).current;
  const sigmaRef = useRef<Sigma | null>(null);

  const { graph, isLoading, error, refresh } = useGraphNetwork();

  const [selectedId, setSelectedId] = useState<number | null>(null);
  const [showHelp, setShowHelp] = useState(false);
  const [layoutReady, setLayoutReady] = useState(false);
  const [optimizing, setOptimizing] = useState(false);

  // Filters
  const [minMomentum, setMinMomentum] = useState(0);
  const [selectedTicker, setSelectedTicker] = useState<string | null>(null);
  const [legendExpanded, setLegendExpanded] = useState(false);
  const [selectedEntities, setSelectedEntities] = useState<string[]>([]);
  const [entityQuery, setEntityQuery] = useState('');
  const [showEntityDropdown, setShowEntityDropdown] = useState(false);
  const [titleQuery, setTitleQuery] = useState('');
  const [filterIsolate, setFilterIsolate] = useState(false);

  // hover is a ref — not React state to avoid cascade on enterNode/leaveNode (50+/sec)
  const hoveredNodeRef = useRef<number | null>(null);

  // Ticker hooks
  const { tickers } = useTickerList();
  const { themes } = useTickerThemes(selectedTicker);

  // Ego network
  const { egoNetwork } = useEgoNetwork(selectedId, 0.05);
  const egoNeighborIds = useMemo<Set<number>>(() => {
    if (!egoNetwork || !selectedId) return new Set();
    return new Set([selectedId, ...egoNetwork.neighbors.map((n) => n.id)]);
  }, [egoNetwork, selectedId]);

  // Raw graph data (from SWR)
  const graphData = graph ?? null;

  // Community rank-based color map
  const { communityColorMap, communityLabels, othersCount, othersNodes } = useMemo(() => {
    if (!graphData) return { communityColorMap: new Map<number, string>(), communityLabels: [], othersCount: 0, othersNodes: 0 };
    const communityMap = new Map<number, { count: number; community_name: string | null }>();
    for (const node of graphData.nodes) {
      const cid = node.community_id;
      if (cid == null) continue;
      if (!communityMap.has(cid)) communityMap.set(cid, { count: 0, community_name: null });
      const entry = communityMap.get(cid)!;
      entry.count++;
      if (!entry.community_name && node.community_name) entry.community_name = node.community_name;
    }
    const allSorted = Array.from(communityMap.entries())
      .map(([cid, { count, community_name }]) => ({ cid, label: community_name || `Community ${cid}`, count }))
      .sort((a, b) => b.count - a.count);
    const colorMap = new Map<number, string>();
    allSorted.forEach(({ cid }, idx) => {
      colorMap.set(cid, idx < TOP_N ? COMMUNITY_PALETTE[idx] : OTHER_COLOR);
    });
    return {
      communityColorMap: colorMap,
      communityLabels: allSorted.slice(0, TOP_N),
      othersCount: Math.max(0, allSorted.length - TOP_N),
      othersNodes: allSorted.slice(TOP_N).reduce((sum, c) => sum + c.count, 0),
    };
  }, [graphData]);

  // Ticker-correlated storylines
  const tickerHighlightIds = useMemo<Set<number>>(() => {
    if (!themes?.themes) return new Set();
    return new Set(themes.themes.map((t) => t.storyline_id));
  }, [themes]);

  // Entity/title highlight IDs (dim mode)
  const entityHighlightIds = useMemo<Set<number>>(() => {
    const hasFilter = selectedEntities.length > 0 || titleQuery.trim();
    if (!hasFilter || filterIsolate || !graphData) return new Set<number>();
    return new Set(
      graphData.nodes
        .filter((n) => {
          const entityMatch =
            selectedEntities.length === 0 ||
            selectedEntities.some((sel) =>
              n.key_entities?.some((ke) => ke.toLowerCase().includes(sel.toLowerCase()))
            );
          const titleMatch = !titleQuery.trim() || n.title.toLowerCase().includes(titleQuery.trim().toLowerCase());
          return entityMatch && titleMatch;
        })
        .map((n) => n.id)
    );
  }, [graphData, selectedEntities, titleQuery, filterIsolate]);

  // Filter state passed into context
  const filterState = useMemo<FilterState>(() => {
    const highlightIds =
      tickerHighlightIds.size > 0 ? tickerHighlightIds : entityHighlightIds;
    return { momentumMin: minMomentum, isolate: filterIsolate, highlightIds };
  }, [minMomentum, filterIsolate, tickerHighlightIds, entityHighlightIds]);

  // Entity autocomplete
  const allEntities = useMemo(
    () =>
      [...new Set((graphData?.nodes ?? []).flatMap((n) => n.key_entities || []))]
        .sort()
        .filter((e) => e.length > 1),
    [graphData]
  );
  const entitySuggestions = useMemo(
    () =>
      entityQuery.length >= 2
        ? allEntities
            .filter((e) => e.toLowerCase().includes(entityQuery.toLowerCase()))
            .filter((e) => !selectedEntities.includes(e))
            .slice(0, 15)
        : [],
    [allEntities, entityQuery, selectedEntities]
  );

  // ── Camera helpers ──────────────────────────────────────────────────────────

  const zoomToFit = useCallback(() => {
    sigmaRef.current?.getCamera().animatedReset({ duration: 400 });
  }, []);

  const handleNavigate = useCallback((id: number) => {
    setSelectedId(id);
    const sigma = sigmaRef.current;
    if (!sigma) return;
    try {
      const attrs = sigma.getGraph().getNodeAttributes(String(id));
      sigma.getCamera().animate({ x: attrs.x as number, y: attrs.y as number, ratio: 0.3 }, { duration: 500 });
    } catch { /* node not in graph */ }
  }, []);

  // Zoom to ticker bounding box when selectedTicker changes
  useEffect(() => {
    if (tickerHighlightIds.size === 0 || !sigmaRef.current || !layoutReady) return;
    const sigma = sigmaRef.current;
    const graph = sigma.getGraph();
    let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity;
    tickerHighlightIds.forEach((id) => {
      try {
        const attrs = graph.getNodeAttributes(String(id));
        if (attrs.x != null && attrs.y != null) {
          minX = Math.min(minX, attrs.x as number);
          minY = Math.min(minY, attrs.y as number);
          maxX = Math.max(maxX, attrs.x as number);
          maxY = Math.max(maxY, attrs.y as number);
        }
      } catch { /* ignore */ }
    });
    if (minX === Infinity) return;
    const cx = (minX + maxX) / 2;
    const cy = (minY + maxY) / 2;
    const span = Math.max(maxX - minX, maxY - minY, 1);
    // ratio: smaller = more zoomed in
    const ratio = Math.min(1, span / 400);
    sigma.getCamera().animate({ x: cx, y: cy, ratio }, { duration: 500 });
  }, [tickerHighlightIds, layoutReady]);

  // Deep-link ?highlight=<id> — navigate after layout is ready
  const highlightApplied = useRef(false);
  useEffect(() => {
    if (!highlightId || !layoutReady || highlightApplied.current) return;
    highlightApplied.current = true;
    const timer = setTimeout(() => {
      handleNavigate(highlightId);
    }, 600);
    return () => clearTimeout(timer);
  }, [highlightId, layoutReady, handleNavigate]);

  return (
    <GraphContext.Provider
      value={{
        selectedId,
        setSelectedId,
        hoveredNodeRef,
        egoNeighborIds,
        filterState,
        communityColorMap,
      }}
    >
      <div className="relative w-full h-[100dvh] bg-[#0A1628] overflow-hidden">
        {/* Sigma WebGL canvas */}
        <SigmaContainer
          graph={sigmaGraph}
          settings={SIGMA_SETTINGS}
          style={{ width: '100%', height: '100%', background: '#0A1628' }}
        >
          <SigmaRefBridge sigmaRef={sigmaRef} />
          <GraphDataLoader
            graphData={graphData}
            communityColorMap={communityColorMap}
            onLayoutReady={() => setLayoutReady(true)}
            onOptimizing={setOptimizing}
          />
          <GraphEvents />
          <GraphStyle />
        </SigmaContainer>

        {/* Community hull + labels SVG overlay (outside SigmaContainer) */}
        {layoutReady && graphData && (
          <CommunityOverlay
            sigmaRef={sigmaRef}
            nodes={graphData.nodes}
            communityColorMap={communityColorMap}
            communityLabels={communityLabels}
          />
        )}

        {/* HUD — Top Left */}
        <div className="absolute top-4 left-4 pointer-events-none">
          <div className="bg-[#0A1628]/80 backdrop-blur-sm border border-[#FF6B35]/30 rounded px-4 py-3">
            <div className="flex items-center gap-2 mb-2">
              <div className="w-2 h-2 bg-[#FF6B35] rounded-full animate-pulse" />
              <span className="text-[#FF6B35] font-mono text-sm font-bold tracking-wider">
                NARRATIVE GRAPH
              </span>
              {optimizing && (
                <span className="text-[10px] font-mono text-yellow-400/70 ml-1 animate-pulse">
                  OPTIMIZING LAYOUT…
                </span>
              )}
            </div>
            {graph?.stats && (
              <div className="space-y-1 text-xs font-mono text-gray-400">
                <div>NODES: <span className="text-white">{graph.stats.total_nodes}</span></div>
                <div>EDGES: <span className="text-white">{graph.stats.total_edges}</span></div>
                <div>COMMUNITIES: <span className="text-white">{graph.stats.communities_count || '—'}</span></div>
                <div>AVG MOMENTUM: <span className="text-white">{graph.stats.avg_momentum.toFixed(2)}</span></div>
                <div>EDGES/NODE: <span className="text-white">{graph.stats.avg_edges_per_node?.toFixed(1) || '—'}</span></div>
              </div>
            )}
            {layoutReady && (
              <button
                type="button"
                onClick={zoomToFit}
                className="pointer-events-auto mt-2 w-full text-[10px] font-mono text-gray-500 hover:text-gray-300 border border-white/10 rounded px-2 py-1 transition-colors"
              >
                ⊞ Zoom to Fit
              </button>
            )}
          </div>
        </div>

        {/* Filters — Top Right */}
        <div className="absolute top-4 right-4 pointer-events-auto">
          {!selectedId && (
            <div className="bg-[#0A1628]/80 backdrop-blur-sm border border-white/10 rounded px-4 py-3 w-[220px]">
              {/* Entity filter */}
              <div className="mb-3">
                <label className="text-xs text-gray-400 uppercase tracking-wider block mb-1">
                  Filter by Entity
                </label>
                <div className="relative">
                  <input
                    type="text"
                    value={entityQuery}
                    onChange={(e) => {
                      setEntityQuery(e.target.value);
                      setShowEntityDropdown(true);
                    }}
                    onFocus={() => setShowEntityDropdown(true)}
                    onBlur={() => setTimeout(() => setShowEntityDropdown(false), 150)}
                    placeholder="e.g. Russia, Kazakhstan…"
                    className="w-full bg-black/60 border border-white/10 rounded text-xs text-gray-300 px-2 py-1.5 placeholder-gray-600 focus:outline-none focus:border-white/25"
                  />
                  {showEntityDropdown && entitySuggestions.length > 0 && (
                    <div className="absolute left-0 right-0 top-full mt-0.5 bg-[#0A1628] border border-white/15 rounded shadow-lg z-50 max-h-40 overflow-y-auto">
                      {entitySuggestions.map((e) => (
                        <button
                          key={e}
                          type="button"
                          onMouseDown={() => {
                            setSelectedEntities((prev) => [...prev, e]);
                            setEntityQuery('');
                            setShowEntityDropdown(false);
                          }}
                          className="w-full text-left text-xs font-mono text-gray-300 px-2 py-1 hover:bg-white/10 transition-colors truncate"
                        >
                          {e}
                        </button>
                      ))}
                    </div>
                  )}
                </div>
                {selectedEntities.length > 0 && (
                  <div className="flex flex-wrap gap-1 mt-1.5">
                    {selectedEntities.map((e) => (
                      <span
                        key={e}
                        className="inline-flex items-center gap-1 bg-[#FF6B35]/20 border border-[#FF6B35]/30 rounded px-1.5 py-0.5 text-[10px] font-mono text-[#FF6B35] max-w-[120px]"
                      >
                        <span className="truncate">{e}</span>
                        <button
                          type="button"
                          onClick={() => setSelectedEntities((prev) => prev.filter((x) => x !== e))}
                          className="flex-shrink-0 hover:text-white transition-colors leading-none"
                        >
                          ×
                        </button>
                      </span>
                    ))}
                    <button
                      type="button"
                      onClick={() => setSelectedEntities([])}
                      className="text-[10px] font-mono text-gray-500 hover:text-gray-300 transition-colors px-1"
                    >
                      clear all
                    </button>
                  </div>
                )}
              </div>

              {/* Title search */}
              <div className="mb-3">
                <label className="text-xs text-gray-400 uppercase tracking-wider block mb-1">
                  Search by Title
                </label>
                <div className="relative">
                  <input
                    type="text"
                    value={titleQuery}
                    onChange={(e) => setTitleQuery(e.target.value)}
                    placeholder="Keyword in title…"
                    className="w-full bg-black/60 border border-white/10 rounded text-xs text-gray-300 px-2 py-1.5 pr-6 placeholder-gray-600 focus:outline-none focus:border-white/25"
                  />
                  {titleQuery && (
                    <button
                      type="button"
                      onClick={() => setTitleQuery('')}
                      className="absolute right-1.5 top-1/2 -translate-y-1/2 text-gray-500 hover:text-gray-300 transition-colors text-xs"
                    >
                      ×
                    </button>
                  )}
                </div>
              </div>

              {/* Isolate toggle */}
              {(selectedEntities.length > 0 || titleQuery.trim()) && (
                <div className="mb-3 flex items-center gap-2">
                  <input
                    id="filter-isolate"
                    type="checkbox"
                    checked={filterIsolate}
                    onChange={(e) => setFilterIsolate(e.target.checked)}
                    className="w-3 h-3 accent-[#FF6B35] cursor-pointer"
                  />
                  <label
                    htmlFor="filter-isolate"
                    className="text-xs font-mono text-gray-400 cursor-pointer select-none"
                  >
                    Show only matches
                  </label>
                </div>
              )}

              {/* Ticker filter */}
              {tickers && (
                <div className="mb-3">
                  <label className="text-xs text-gray-400 uppercase tracking-wider block mb-1">
                    Filter by Ticker
                  </label>
                  <select
                    aria-label="Filter storylines by market ticker"
                    value={selectedTicker ?? ''}
                    onChange={(e) => setSelectedTicker(e.target.value || null)}
                    className="w-full bg-black/60 border border-white/10 rounded text-xs text-gray-300 px-2 py-1.5 cursor-pointer"
                  >
                    <option value="">All Tickers</option>
                    {Object.entries(tickers.categories).map(([cat, entries]) => (
                      <optgroup key={cat} label={cat.toUpperCase()}>
                        {entries.map((e) => (
                          <option key={e.ticker} value={e.ticker}>
                            {e.ticker} — {e.name}
                          </option>
                        ))}
                      </optgroup>
                    ))}
                  </select>
                  {selectedTicker && (
                    <button
                      onClick={() => setSelectedTicker(null)}
                      className="mt-1 text-xs text-gray-500 hover:text-gray-300 transition-colors"
                      type="button"
                    >
                      Clear filter ×
                    </button>
                  )}
                </div>
              )}

              {/* Momentum slider */}
              <div className="mb-3">
                <div className="flex justify-between text-xs font-mono text-gray-500 mb-1">
                  <span className="uppercase">Min Momentum</span>
                  <span className="text-white">{minMomentum.toFixed(1)}</span>
                </div>
                <input
                  type="range"
                  aria-label="Minimum momentum filter"
                  min={0}
                  max={1}
                  step={0.1}
                  value={minMomentum}
                  onChange={(e) => setMinMomentum(parseFloat(e.target.value))}
                  className="w-full h-1 accent-[#FF6B35] cursor-pointer"
                />
              </div>

              {/* Community legend */}
              {communityLabels.length > 0 && (
                <>
                  <button
                    type="button"
                    onClick={() => setLegendExpanded((v) => !v)}
                    className="flex items-center justify-between w-full text-xs font-mono text-gray-500 mb-2 uppercase hover:text-gray-300 transition-colors"
                  >
                    <span>Communities ({communityLabels.length + (othersCount > 0 ? 1 : 0)})</span>
                    <span className="ml-2 text-gray-600">{legendExpanded ? '▲' : '▼'}</span>
                  </button>
                  {legendExpanded && (
                    <div className="space-y-1.5">
                      {communityLabels.map(({ cid, label, count }) => (
                        <div key={cid} className="flex items-start gap-2">
                          <div
                            className="w-3 h-3 rounded-full flex-shrink-0 mt-0.5"
                            style={{ backgroundColor: communityColorMap.get(cid) || OTHER_COLOR }}
                          />
                          <span className="text-xs font-mono text-gray-300 flex-1 leading-tight">{label}</span>
                          <span className="text-xs font-mono text-gray-600 flex-shrink-0">{count}</span>
                        </div>
                      ))}
                      {othersCount > 0 && (
                        <div className="flex items-center gap-2 mt-1 pt-1 border-t border-white/5">
                          <div className="w-3 h-3 rounded-full flex-shrink-0" style={{ backgroundColor: OTHER_COLOR }} />
                          <span className="text-xs font-mono text-gray-500 flex-1">Others ({othersCount})</span>
                          <span className="text-xs font-mono text-gray-600 flex-shrink-0">{othersNodes}</span>
                        </div>
                      )}
                    </div>
                  )}
                </>
              )}
            </div>
          )}

          {/* Help button */}
          <button
            type="button"
            onClick={() => setShowHelp(true)}
            className="mt-2 flex items-center gap-2 px-3 py-1.5 rounded border border-white/10 bg-[#0A1628]/80 backdrop-blur-sm text-gray-400 hover:text-white hover:border-white/30 transition-all font-mono text-[10px] uppercase tracking-wider w-full justify-center"
          >
            ? Guide
          </button>
        </div>

        {/* Loading overlay */}
        {isLoading && !graph && (
          <div className="absolute inset-0 flex items-center justify-center bg-[#0A1628]/80">
            <div className="text-center">
              <div className="w-12 h-12 border-2 border-[#FF6B35] border-t-transparent rounded-full animate-spin mx-auto mb-4" />
              <div className="text-[#FF6B35] font-mono text-sm">Loading graph data...</div>
            </div>
          </div>
        )}

        {/* Error state */}
        {error && !graph && (
          <div className="absolute inset-0 flex items-center justify-center bg-[#0A1628]/80">
            <div className="text-center max-w-md">
              <div className="text-red-400 font-mono text-lg mb-2">Connection Error</div>
              <div className="text-gray-400 font-mono text-sm mb-4">
                Unable to load narrative graph data. Make sure the API server is running.
              </div>
              <button
                type="button"
                onClick={() => refresh()}
                className="px-4 py-2 bg-[#FF6B35]/20 border border-[#FF6B35]/40 text-[#FF6B35] font-mono text-sm rounded hover:bg-[#FF6B35]/30 transition-colors"
              >
                RETRY
              </button>
            </div>
          </div>
        )}

        {/* Empty state */}
        {!isLoading && !error && graph && graph.nodes.length === 0 && (
          <div className="absolute inset-0 flex items-center justify-center">
            <div className="text-center">
              <div className="text-gray-500 font-mono text-lg mb-2">No Active Storylines</div>
              <div className="text-gray-600 font-mono text-sm">
                Run the narrative pipeline to generate storylines.
              </div>
            </div>
          </div>
        )}

        {/* Storyline Dossier Panel */}
        <StorylineDossier
          storylineId={selectedId}
          onClose={() => setSelectedId(null)}
          onNavigate={handleNavigate}
        />

        {/* Corner brackets */}
        <div className="absolute top-2 left-2 w-8 h-8 border-l-2 border-t-2 border-[#FF6B35]/30 pointer-events-none" />
        <div className="absolute top-2 right-2 w-8 h-8 border-r-2 border-t-2 border-[#FF6B35]/30 pointer-events-none" />
        <div className="absolute bottom-2 left-2 w-8 h-8 border-l-2 border-b-2 border-[#FF6B35]/30 pointer-events-none" />
        <div className="absolute bottom-2 right-2 w-8 h-8 border-r-2 border-b-2 border-[#FF6B35]/30 pointer-events-none" />

        {/* Help modal */}
        <HelpModal
          open={showHelp}
          onClose={() => setShowHelp(false)}
          title="Narrative Graph Guide"
          subtitle="How to navigate the storyline network"
          intro="The Narrative Graph is a WebGL network of active geopolitical storylines rendered with Sigma.js. Nodes are storylines; edges are narrative connections based on shared entities. The layout is computed by ForceAtlas2 in a web worker."
          sections={STORIES_GUIDE_SECTIONS}
        />
      </div>
    </GraphContext.Provider>
  );
}
