'use client';

import '@react-sigma/core/lib/style.css';

import { useCallback, useEffect, useRef, useState, useMemo } from 'react';
import { SigmaContainer, useSigma } from '@react-sigma/core';
import { UndirectedGraph } from 'graphology';
import type Sigma from 'sigma';
import { useGraphNetwork, useEgoNetwork } from '@/hooks/useStories';
import StorylineDossier from './StorylineDossier';
import GraphDataLoader from './GraphDataLoader';
import GraphEvents from './GraphEvents';
import GraphStyle from './GraphStyle';
import CommunityOverlay from './CommunityOverlay';
import { GraphContext } from './GraphContext';
import type { HoverInfo } from './GraphContext';
import type { StorylineNode } from '@/types/stories';
import { useGraphFilters } from './useGraphFilters';
import { HelpModal } from '@/components/HelpModal';
import type { HelpSection } from '@/components/HelpModal';
import { COMMUNITY_OTHER } from '@/lib/communityColors';

const OTHER_COLOR = COMMUNITY_OTHER;

// ── SigmaRefBridge ────────────────────────────────────────────────────────────
// Bridges the sigma instance (only accessible inside SigmaContainer) to a ref
// in the parent, so CommunityOverlay and camera controls can use it.
function SigmaRefBridge({ sigmaRef }: { sigmaRef: React.MutableRefObject<Sigma | null> }) {
  const sigma = useSigma();
  useEffect(() => {
    sigmaRef.current = sigma;
    return () => { sigmaRef.current = null; };
  }, [sigma, sigmaRef]);
  return null;
}

const SIGMA_SETTINGS = {
  renderLabels: true,
  labelFont: '-apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
  labelSize: 12,
  labelColor: { color: '#E0E0E0' },
  labelRenderedSizeThreshold: 8,
  hideLabelsOnMove: true,
  defaultEdgeColor: 'rgba(150,190,220,0.08)',
  defaultNodeColor: '#00A8E8',
  minCameraRatio: 0.05,
  maxCameraRatio: 5,
  enableEdgeEvents: false,
  hideEdgesOnMove: true,
};

const STORIES_GUIDE_SECTIONS: HelpSection[] = [
  {
    key: 'nodes',
    label: 'Nodes — Storylines',
    labelColor: 'text-orange-300',
    bgColor: 'bg-orange-500/8 border-orange-500/15',
    content: 'Each node is an active narrative storyline. Node size reflects momentum score — larger nodes are gaining coverage. Hover to see the title and article count; click to open the full dossier.',
  },
  {
    key: 'colors',
    label: 'Colors — Communities',
    labelColor: 'text-purple-300',
    bgColor: 'bg-purple-500/8 border-purple-500/15',
    content: 'Colors represent Louvain-detected thematic communities. Up to 15 distinct communities are shown; all others appear in dark gray. Community names are generated by Gemini and shown in the legend.',
  },
  {
    key: 'edges',
    label: 'Edges — Narrative Links',
    labelColor: 'text-cyan-300',
    bgColor: 'bg-cyan-500/8 border-cyan-500/15',
    content: 'Lines connect storylines that share key entities. Edge thickness and opacity correspond to TF-IDF weighted Jaccard similarity — thicker lines indicate stronger narrative overlap.',
  },
  {
    key: 'ego',
    label: 'Ego Network',
    labelColor: 'text-blue-300',
    bgColor: 'bg-blue-500/8 border-blue-500/15',
    content: 'Click a node to enter ego-network mode: the selected node\'s direct neighbors are highlighted. Other nodes become ghost outlines. Click the same node again or press Escape to exit.',
  },
  {
    key: 'filters',
    label: 'Filters',
    labelColor: 'text-green-300',
    bgColor: 'bg-green-500/8 border-green-500/15',
    content: 'Momentum slider — hide storylines below a minimum momentum. Ticker filter — select a market ticker to highlight storylines related to that asset. Community legend — click to isolate.',
    tip: 'Use the ticker filter to find geopolitical narratives with direct market relevance.',
  },
  {
    key: 'status',
    label: 'Status — Node Age',
    labelColor: 'text-yellow-300',
    bgColor: 'bg-yellow-500/8 border-yellow-500/15',
    content: 'Emerging — new storylines (< 3 days). Active — developing threads with recent updates. Stabilized — established narratives with lower but steady activity.',
  },
];

interface StorylineGraphProps {
  highlightId?: number | null;
}

export default function StorylineGraph({ highlightId = null }: StorylineGraphProps) {
  // Stable graphology graph object — never recreated, SigmaContainer holds the WebGL context
  const sigmaGraph = useRef(new UndirectedGraph()).current;
  const sigmaRef = useRef<Sigma | null>(null);

  const { graph, isLoading, error, refresh } = useGraphNetwork();

  const [selectedId, setSelectedId] = useState<number | null>(null);
  const [showHelp, setShowHelp] = useState(false);
  const [layoutReady, setLayoutReady] = useState(false);
  const [optimizing, setOptimizing] = useState(false);

  // hover is a ref — not React state — so nodeReducer can read it without a
  // React re-render. Tooltip info is separate state, updated only on enter/leave.
  const hoveredNodeRef = useRef<number | null>(null);
  const [hoverInfo, setHoverInfo] = useState<HoverInfo | null>(null);

  // Raw graph data (from SWR)
  const graphData = graph ?? null;

  // All filter state + derivations live in the hook (business logic)
  const {
    minMomentum, setMinMomentum,
    selectedTicker, setSelectedTicker,
    legendExpanded, setLegendExpanded,
    selectedEntities, setSelectedEntities,
    entityQuery, setEntityQuery,
    showEntityDropdown, setShowEntityDropdown,
    titleQuery, setTitleQuery,
    filterIsolate, setFilterIsolate,
    showNew, setShowNew,
    tickers,
    communityColorMap, communityLabels, othersCount, othersNodes,
    tickerHighlightIds,
    filterState,
    entitySuggestions,
  } = useGraphFilters(graphData);

  // Ego network
  const { egoNetwork } = useEgoNetwork(selectedId, 0.05);
  const egoNeighborIds = useMemo<Set<number>>(() => {
    if (!egoNetwork || !selectedId) return new Set();
    return new Set([selectedId, ...egoNetwork.neighbors.map((n) => n.id)]);
  }, [egoNetwork, selectedId]);

  // O(1) lookup for the hover tooltip (full node payload by id)
  const nodeById = useMemo(() => {
    const m = new Map<number, StorylineNode>();
    if (graphData) for (const n of graphData.nodes) m.set(n.id, n);
    return m;
  }, [graphData]);
  const hoveredNode = hoverInfo ? nodeById.get(hoverInfo.id) ?? null : null;

  // "Why are these connected?" — the edge weight is a Jaccard over key_entities,
  // so the intersection of the two nodes' entity lists is the connection reason.
  // Computed client-side from data already present (no API/edge column needed).
  const getSharedEntities = useCallback(
    (otherId: number): string[] => {
      if (selectedId == null || otherId === selectedId) return [];
      const a = nodeById.get(selectedId)?.key_entities;
      const b = nodeById.get(otherId)?.key_entities;
      if (!a?.length || !b?.length) return [];
      const setB = new Set(b.map((e) => e.toLowerCase()));
      return a.filter((e) => setB.has(e.toLowerCase()));
    },
    [selectedId, nodeById]
  );

  // Shared entities to show in the tooltip when hovering a neighbor in ego mode
  const hoverShared =
    hoverInfo && selectedId != null && hoverInfo.id !== selectedId
      ? getSharedEntities(hoverInfo.id)
      : [];

  // Navigation trail — the chain of storylines visited node→neighbor→neighbor.
  // Lets the analyst back-track without losing the starting point. Derived from
  // selectedId changes: re-visiting a node in the trail truncates back to it;
  // clearing the selection (click on empty stage) resets the trail.
  const [navHistory, setNavHistory] = useState<number[]>([]);
  useEffect(() => {
    if (selectedId == null) {
      setNavHistory([]);
      return;
    }
    setNavHistory((prev) => {
      if (prev[prev.length - 1] === selectedId) return prev;
      const idx = prev.indexOf(selectedId);
      if (idx !== -1) return prev.slice(0, idx + 1); // went back to an earlier node
      return [...prev, selectedId];
    });
  }, [selectedId]);

  // ── Camera helpers ──────────────────────────────────────────────────────────

  const zoomToFit = useCallback(() => {
    sigmaRef.current?.getCamera().animatedReset({ duration: 400 });
  }, []);

  const zoomBy = useCallback((factor: number) => {
    const camera = sigmaRef.current?.getCamera();
    if (!camera) return;
    camera.animate({ ratio: camera.ratio * factor }, { duration: 250 });
  }, []);

  const handleNavigate = useCallback((id: number) => {
    setSelectedId(id);
    const sigma = sigmaRef.current;
    if (!sigma) return;
    try {
      const attrs = sigma.getGraph().getNodeAttributes(String(id));
      sigma.getCamera().animate({ x: attrs.x as number, y: attrs.y as number, ratio: 0.3 }, { duration: 500 });
    } catch { /* node not in graph */ }
  }, []);

  // Zoom to ticker bounding box when selectedTicker changes
  useEffect(() => {
    if (tickerHighlightIds.size === 0 || !sigmaRef.current || !layoutReady) return;
    const sigma = sigmaRef.current;
    const graph = sigma.getGraph();
    let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity;
    tickerHighlightIds.forEach((id) => {
      try {
        const attrs = graph.getNodeAttributes(String(id));
        if (attrs.x != null && attrs.y != null) {
          minX = Math.min(minX, attrs.x as number);
          minY = Math.min(minY, attrs.y as number);
          maxX = Math.max(maxX, attrs.x as number);
          maxY = Math.max(maxY, attrs.y as number);
        }
      } catch { /* ignore */ }
    });
    if (minX === Infinity) return;
    const cx = (minX + maxX) / 2;
    const cy = (minY + maxY) / 2;
    const span = Math.max(maxX - minX, maxY - minY, 1);
    // ratio: smaller = more zoomed in
    const ratio = Math.min(1, span / 400);
    sigma.getCamera().animate({ x: cx, y: cy, ratio }, { duration: 500 });
  }, [tickerHighlightIds, layoutReady]);

  // Deep-link ?highlight=<id> — navigate after layout is ready
  const highlightApplied = useRef(false);
  useEffect(() => {
    if (!highlightId || !layoutReady || highlightApplied.current) return;
    highlightApplied.current = true;
    const timer = setTimeout(() => {
      handleNavigate(highlightId);
    }, 600);
    return () => clearTimeout(timer);
  }, [highlightId, layoutReady, handleNavigate]);

  return (
    <GraphContext.Provider
      value={{
        selectedId,
        setSelectedId,
        hoveredNodeRef,
        egoNeighborIds,
        filterState,
        communityColorMap,
        onHoverNode: setHoverInfo,
      }}
    >
      <div className="relative w-full h-[100dvh] bg-[#0A1628] overflow-hidden">
        {/* Sigma WebGL canvas */}
        <SigmaContainer
          graph={sigmaGraph}
          settings={SIGMA_SETTINGS}
          style={{ width: '100%', height: '100%', background: '#0A1628' }}
        >
          <SigmaRefBridge sigmaRef={sigmaRef} />
          <GraphDataLoader
            graphData={graphData}
            communityColorMap={communityColorMap}
            onLayoutReady={() => setLayoutReady(true)}
            onOptimizing={setOptimizing}
          />
          <GraphEvents />
          <GraphStyle />
        </SigmaContainer>

        {/* Community hull + labels SVG overlay (outside SigmaContainer) */}
        {layoutReady && graphData && (
          <CommunityOverlay
            sigmaRef={sigmaRef}
            nodes={graphData.nodes}
            communityColorMap={communityColorMap}
            communityLabels={communityLabels}
          />
        )}

        {/* Navigation trail — back-track the exploration chain without losing the start */}
        {navHistory.length > 1 && (
          <div className="absolute top-4 left-1/2 -translate-x-1/2 z-30 max-w-[60vw] hidden md:flex items-center gap-1 bg-[#0A1628]/80 backdrop-blur-sm border border-white/10 rounded px-2 py-1.5">
            {navHistory.map((id, i) => {
              const isLast = i === navHistory.length - 1;
              const title = nodeById.get(id)?.title ?? `#${id}`;
              return (
                <span key={id} className="flex items-center gap-1 min-w-0">
                  {i > 0 && <span className="text-gray-600 text-xs flex-shrink-0">›</span>}
                  <button
                    type="button"
                    onClick={() => !isLast && handleNavigate(id)}
                    disabled={isLast}
                    title={title}
                    className={`text-[11px] font-mono truncate max-w-[160px] transition-colors ${
                      isLast
                        ? 'text-[#FF6B35] cursor-default'
                        : 'text-gray-400 hover:text-white cursor-pointer'
                    }`}
                  >
                    {title}
                  </button>
                </span>
              );
            })}
          </div>
        )}

        {/* Hover tooltip — title, status, momentum, article count */}
        {hoverInfo && hoveredNode && (
          <div
            className="absolute z-40 pointer-events-none max-w-[260px] bg-[#0A1628]/95 backdrop-blur-sm border border-white/15 rounded px-3 py-2 shadow-xl"
            style={{
              left: hoverInfo.x,
              top: hoverInfo.y,
              transform: `translate(${hoverInfo.x > 0 ? '12px' : '0'}, -50%)`,
            }}
          >
            <div className="text-xs text-white font-semibold leading-tight mb-1 line-clamp-3">
              {hoveredNode.title}
            </div>
            <div className="flex items-center gap-2 text-[10px] font-mono">
              <span
                className={
                  hoveredNode.narrative_status === 'emerging'
                    ? 'text-[#FF6B35]'
                    : hoveredNode.narrative_status === 'active'
                    ? 'text-[#00A8E8]'
                    : 'text-gray-400'
                }
              >
                {hoveredNode.narrative_status.toUpperCase()}
              </span>
              <span className="text-gray-600">·</span>
              <span className="text-gray-300">M {hoveredNode.momentum_score.toFixed(2)}</span>
              <span className="text-gray-600">·</span>
              <span className="text-gray-300">{hoveredNode.article_count} art.</span>
            </div>
            {hoverShared.length > 0 ? (
              <div className="mt-1.5 pt-1.5 border-t border-white/10 text-[10px] font-mono">
                <span className="text-[#FF6B35]">↔ shared: </span>
                <span className="text-gray-300">{hoverShared.slice(0, 5).join(' · ')}</span>
              </div>
            ) : (
              hoveredNode.key_entities?.length > 0 && (
                <div className="mt-1 text-[10px] font-mono text-gray-500 truncate">
                  {hoveredNode.key_entities.slice(0, 4).join(' · ')}
                </div>
              )
            )}
          </div>
        )}

        {/* HUD — Top Left */}
        <div className="absolute top-4 left-4 pointer-events-none">
          <div className="bg-[#0A1628]/80 backdrop-blur-sm border border-[#FF6B35]/30 rounded px-4 py-3">
            <div className="flex items-center gap-2 mb-2">
              <div className="w-2 h-2 bg-[#FF6B35] rounded-full animate-pulse" />
              <span className="text-[#FF6B35] font-mono text-sm font-bold tracking-wider">
                NARRATIVE GRAPH
              </span>
              {optimizing && (
                <span className="text-[10px] font-mono text-yellow-400/70 ml-1 animate-pulse">
                  OPTIMIZING LAYOUT…
                </span>
              )}
            </div>
            {graph?.stats && (
              <div className="space-y-1 text-xs font-mono text-gray-400">
                <div>NODES: <span className="text-white">{graph.stats.total_nodes}</span></div>
                <div>EDGES: <span className="text-white">{graph.stats.total_edges}</span></div>
                <div>COMMUNITIES: <span className="text-white">{graph.stats.communities_count || '—'}</span></div>
                <div>AVG MOMENTUM: <span className="text-white">{graph.stats.avg_momentum.toFixed(2)}</span></div>
                <div>EDGES/NODE: <span className="text-white">{graph.stats.avg_edges_per_node?.toFixed(1) || '—'}</span></div>
              </div>
            )}
            {layoutReady && (
              <div className="pointer-events-auto mt-2 flex gap-1">
                <button
                  type="button"
                  onClick={() => zoomBy(1 / 1.4)}
                  aria-label="Zoom in"
                  className="flex-1 text-[12px] leading-none font-mono text-gray-400 hover:text-white border border-white/10 rounded py-1.5 transition-colors"
                >
                  +
                </button>
                <button
                  type="button"
                  onClick={() => zoomBy(1.4)}
                  aria-label="Zoom out"
                  className="flex-1 text-[12px] leading-none font-mono text-gray-400 hover:text-white border border-white/10 rounded py-1.5 transition-colors"
                >
                  −
                </button>
                <button
                  type="button"
                  onClick={zoomToFit}
                  className="flex-[2] text-[10px] font-mono text-gray-500 hover:text-gray-300 border border-white/10 rounded px-2 py-1 transition-colors"
                >
                  ⊞ Fit
                </button>
              </div>
            )}

            {/* Always-visible key — answers "what am I looking at?" without opening a menu */}
            <div className="mt-2 pt-2 border-t border-white/5 space-y-1 text-[10px] font-mono text-gray-500">
              <div className="flex items-center gap-2">
                <span className="flex items-end gap-0.5">
                  <span className="w-1 h-1 rounded-full bg-gray-400" />
                  <span className="w-2 h-2 rounded-full bg-gray-300" />
                </span>
                size = momentum
              </div>
              <div className="flex items-center gap-2">
                <span className="flex gap-0.5">
                  <span className="w-2 h-2 rounded-full bg-[#FF6B35]" />
                  <span className="w-2 h-2 rounded-full bg-[#00A8E8]" />
                </span>
                color = theme
              </div>
              <div className="flex items-center gap-2">
                <span className="w-2 h-2 rounded-full bg-[#FF6B35] animate-pulse" />
                <span className="text-[#FF6B35]">new (&lt; 3d)</span>
              </div>
            </div>
          </div>
        </div>

        {/* Filters — Top Right */}
        <div className="absolute top-4 right-4 pointer-events-auto">
          {!selectedId && (
            <div className="bg-[#0A1628]/80 backdrop-blur-sm border border-white/10 rounded px-4 py-3 w-[220px]">
              {/* Entity filter */}
              <div className="mb-3">
                <label className="text-xs text-gray-400 uppercase tracking-wider block mb-1">
                  Filter by Entity
                </label>
                <div className="relative">
                  <input
                    type="text"
                    value={entityQuery}
                    onChange={(e) => {
                      setEntityQuery(e.target.value);
                      setShowEntityDropdown(true);
                    }}
                    onFocus={() => setShowEntityDropdown(true)}
                    onBlur={() => setTimeout(() => setShowEntityDropdown(false), 150)}
                    placeholder="e.g. Russia, Kazakhstan…"
                    className="w-full bg-black/60 border border-white/10 rounded text-xs text-gray-300 px-2 py-1.5 placeholder-gray-600 focus:outline-none focus:border-white/25"
                  />
                  {showEntityDropdown && entitySuggestions.length > 0 && (
                    <div className="absolute left-0 right-0 top-full mt-0.5 bg-[#0A1628] border border-white/15 rounded shadow-lg z-50 max-h-40 overflow-y-auto">
                      {entitySuggestions.map((e) => (
                        <button
                          key={e}
                          type="button"
                          onMouseDown={() => {
                            setSelectedEntities((prev) => [...prev, e]);
                            setEntityQuery('');
                            setShowEntityDropdown(false);
                          }}
                          className="w-full text-left text-xs font-mono text-gray-300 px-2 py-1 hover:bg-white/10 transition-colors truncate"
                        >
                          {e}
                        </button>
                      ))}
                    </div>
                  )}
                </div>
                {selectedEntities.length > 0 && (
                  <div className="flex flex-wrap gap-1 mt-1.5">
                    {selectedEntities.map((e) => (
                      <span
                        key={e}
                        className="inline-flex items-center gap-1 bg-[#FF6B35]/20 border border-[#FF6B35]/30 rounded px-1.5 py-0.5 text-[10px] font-mono text-[#FF6B35] max-w-[120px]"
                      >
                        <span className="truncate">{e}</span>
                        <button
                          type="button"
                          onClick={() => setSelectedEntities((prev) => prev.filter((x) => x !== e))}
                          className="flex-shrink-0 hover:text-white transition-colors leading-none"
                        >
                          ×
                        </button>
                      </span>
                    ))}
                    <button
                      type="button"
                      onClick={() => setSelectedEntities([])}
                      className="text-[10px] font-mono text-gray-500 hover:text-gray-300 transition-colors px-1"
                    >
                      clear all
                    </button>
                  </div>
                )}
              </div>

              {/* Title search */}
              <div className="mb-3">
                <label className="text-xs text-gray-400 uppercase tracking-wider block mb-1">
                  Search by Title
                </label>
                <div className="relative">
                  <input
                    type="text"
                    value={titleQuery}
                    onChange={(e) => setTitleQuery(e.target.value)}
                    placeholder="Keyword in title…"
                    className="w-full bg-black/60 border border-white/10 rounded text-xs text-gray-300 px-2 py-1.5 pr-6 placeholder-gray-600 focus:outline-none focus:border-white/25"
                  />
                  {titleQuery && (
                    <button
                      type="button"
                      onClick={() => setTitleQuery('')}
                      className="absolute right-1.5 top-1/2 -translate-y-1/2 text-gray-500 hover:text-gray-300 transition-colors text-xs"
                    >
                      ×
                    </button>
                  )}
                </div>
              </div>

              {/* Isolate toggle */}
              {(selectedEntities.length > 0 || titleQuery.trim()) && (
                <div className="mb-3 flex items-center gap-2">
                  <input
                    id="filter-isolate"
                    type="checkbox"
                    checked={filterIsolate}
                    onChange={(e) => setFilterIsolate(e.target.checked)}
                    className="w-3 h-3 accent-[#FF6B35] cursor-pointer"
                  />
                  <label
                    htmlFor="filter-isolate"
                    className="text-xs font-mono text-gray-400 cursor-pointer select-none"
                  >
                    Show only matches
                  </label>
                </div>
              )}

              {/* Ticker filter */}
              {tickers && (
                <div className="mb-3">
                  <label className="text-xs text-gray-400 uppercase tracking-wider block mb-1">
                    Filter by Ticker
                  </label>
                  <select
                    aria-label="Filter storylines by market ticker"
                    value={selectedTicker ?? ''}
                    onChange={(e) => setSelectedTicker(e.target.value || null)}
                    className="w-full bg-black/60 border border-white/10 rounded text-xs text-gray-300 px-2 py-1.5 cursor-pointer"
                  >
                    <option value="">All Tickers</option>
                    {Object.entries(tickers.categories).map(([cat, entries]) => (
                      <optgroup key={cat} label={cat.toUpperCase()}>
                        {entries.map((e) => (
                          <option key={e.ticker} value={e.ticker}>
                            {e.ticker} — {e.name}
                          </option>
                        ))}
                      </optgroup>
                    ))}
                  </select>
                  {selectedTicker && (
                    <button
                      onClick={() => setSelectedTicker(null)}
                      className="mt-1 text-xs text-gray-500 hover:text-gray-300 transition-colors"
                      type="button"
                    >
                      Clear filter ×
                    </button>
                  )}
                </div>
              )}

              {/* Momentum slider */}
              <div className="mb-3">
                <div className="flex justify-between text-xs font-mono text-gray-500 mb-1">
                  <span className="uppercase">Min Momentum</span>
                  <span className="text-white">{minMomentum.toFixed(1)}</span>
                </div>
                <input
                  type="range"
                  aria-label="Minimum momentum filter"
                  min={0}
                  max={1}
                  step={0.1}
                  value={minMomentum}
                  onChange={(e) => setMinMomentum(parseFloat(e.target.value))}
                  className="w-full h-1 accent-[#FF6B35] cursor-pointer"
                />
              </div>

              {/* Novità — highlight emerging storylines */}
              <button
                type="button"
                onClick={() => setShowNew((v) => !v)}
                className={`mb-3 flex items-center gap-2 w-full text-left transition-colors ${
                  showNew ? 'text-[#FF6B35]' : 'text-gray-400 hover:text-gray-200'
                }`}
              >
                <span className={`w-2 h-2 rounded-full bg-[#FF6B35] ${showNew ? 'animate-pulse' : 'opacity-40'}`} />
                <span className="text-xs font-mono uppercase tracking-wider">Novità (emerging)</span>
              </button>

              {/* Community legend */}
              {communityLabels.length > 0 && (
                <>
                  <button
                    type="button"
                    onClick={() => setLegendExpanded((v) => !v)}
                    className="flex items-center justify-between w-full text-xs font-mono text-gray-500 mb-2 uppercase hover:text-gray-300 transition-colors"
                  >
                    <span>Communities ({communityLabels.length + (othersCount > 0 ? 1 : 0)})</span>
                    <span className="ml-2 text-gray-600">{legendExpanded ? '▲' : '▼'}</span>
                  </button>
                  {legendExpanded && (
                    <div className="space-y-1.5">
                      {communityLabels.map(({ cid, label, count }) => (
                        <div key={cid} className="flex items-start gap-2">
                          <div
                            className="w-3 h-3 rounded-full flex-shrink-0 mt-0.5"
                            style={{ backgroundColor: communityColorMap.get(cid) || OTHER_COLOR }}
                          />
                          <span className="text-xs font-mono text-gray-300 flex-1 leading-tight">{label}</span>
                          <span className="text-xs font-mono text-gray-600 flex-shrink-0">{count}</span>
                        </div>
                      ))}
                      {othersCount > 0 && (
                        <div className="flex items-center gap-2 mt-1 pt-1 border-t border-white/5">
                          <div className="w-3 h-3 rounded-full flex-shrink-0" style={{ backgroundColor: OTHER_COLOR }} />
                          <span className="text-xs font-mono text-gray-500 flex-1">Others ({othersCount})</span>
                          <span className="text-xs font-mono text-gray-600 flex-shrink-0">{othersNodes}</span>
                        </div>
                      )}
                    </div>
                  )}
                </>
              )}
            </div>
          )}

          {/* Help button */}
          <button
            type="button"
            onClick={() => setShowHelp(true)}
            className="mt-2 flex items-center gap-2 px-3 py-1.5 rounded border border-white/10 bg-[#0A1628]/80 backdrop-blur-sm text-gray-400 hover:text-white hover:border-white/30 transition-all font-mono text-[10px] uppercase tracking-wider w-full justify-center"
          >
            ? Guide
          </button>
        </div>

        {/* Loading overlay */}
        {isLoading && !graph && (
          <div className="absolute inset-0 flex items-center justify-center bg-[#0A1628]/80">
            <div className="text-center">
              <div className="w-12 h-12 border-2 border-[#FF6B35] border-t-transparent rounded-full animate-spin mx-auto mb-4" />
              <div className="text-[#FF6B35] font-mono text-sm">Loading graph data...</div>
            </div>
          </div>
        )}

        {/* Error state */}
        {error && !graph && (
          <div className="absolute inset-0 flex items-center justify-center bg-[#0A1628]/80">
            <div className="text-center max-w-md">
              <div className="text-red-400 font-mono text-lg mb-2">Connection Error</div>
              <div className="text-gray-400 font-mono text-sm mb-4">
                Unable to load narrative graph data. Make sure the API server is running.
              </div>
              <button
                type="button"
                onClick={() => refresh()}
                className="px-4 py-2 bg-[#FF6B35]/20 border border-[#FF6B35]/40 text-[#FF6B35] font-mono text-sm rounded hover:bg-[#FF6B35]/30 transition-colors"
              >
                RETRY
              </button>
            </div>
          </div>
        )}

        {/* Empty state */}
        {!isLoading && !error && graph && graph.nodes.length === 0 && (
          <div className="absolute inset-0 flex items-center justify-center">
            <div className="text-center">
              <div className="text-gray-500 font-mono text-lg mb-2">No Active Storylines</div>
              <div className="text-gray-600 font-mono text-sm">
                Run the narrative pipeline to generate storylines.
              </div>
            </div>
          </div>
        )}

        {/* Storyline Dossier Panel */}
        <StorylineDossier
          storylineId={selectedId}
          onClose={() => setSelectedId(null)}
          onNavigate={handleNavigate}
          getSharedEntities={getSharedEntities}
        />

        {/* Corner brackets */}
        <div className="absolute top-2 left-2 w-8 h-8 border-l-2 border-t-2 border-[#FF6B35]/30 pointer-events-none" />
        <div className="absolute top-2 right-2 w-8 h-8 border-r-2 border-t-2 border-[#FF6B35]/30 pointer-events-none" />
        <div className="absolute bottom-2 left-2 w-8 h-8 border-l-2 border-b-2 border-[#FF6B35]/30 pointer-events-none" />
        <div className="absolute bottom-2 right-2 w-8 h-8 border-r-2 border-b-2 border-[#FF6B35]/30 pointer-events-none" />

        {/* Help modal */}
        <HelpModal
          open={showHelp}
          onClose={() => setShowHelp(false)}
          title="Narrative Graph Guide"
          subtitle="How to navigate the storyline network"
          intro="The Narrative Graph is a WebGL network of active geopolitical storylines rendered with Sigma.js. Nodes are storylines; edges are narrative connections based on shared entities. The layout is computed by ForceAtlas2 in a web worker."
          sections={STORIES_GUIDE_SECTIONS}
        />
      </div>
    </GraphContext.Provider>
  );
}
